# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8b56de92eecf458cc7ebadad900833741c1ed036edc08d4d1d568ce3e1f24ed0b7914da6f2b9f297f5aa333c91b4fac3142986fe9619cafb2eb2bca70a0e2b3

test:
  secret_key_base: 810c61444ae4dd71fd59644554961b02629e4c4197d842ccdb150788d69d792c9b512d6c2a43ff3bb3da8328c333bafaad4ce286aa17e0295e90f3cffc0a1f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
